### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by FloydZ** [FloydZ/python_x86instruction_throughput#4]
- [ ] std::cout printing instead printf
- [ ] better cmd args parsing
- [ ] cmake submodules downloading building and stuff
- [ ] builtin the following args:
	- only one thread
	- json output
- [ ] display backends abstract away via concepts
- [ ] cpp futures?
